name: Build and test

on:
  pull_request:


jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup environments
        run: |
          sudo apt-get -yqq update && \
          sudo apt-get -yqq install cmake lcov ninja-build libopencv-dev libeigen3-dev python3-pip
          pip install gcovr

      - name: Build and test
        run: |
          cd ${{ github.workspace }}
          mkdir -p build
          cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build -G Ninja \
              && cmake --build build \
              && cd build \
              && ctest --output-on-failure

      - name: gcovr coverage report
        run: |
          gcovr --filter include/ --filter src/
